import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import { Providers } from "./providers";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Providers>
          <Box bg="green.500">
            <Box maxW="1170px" margin="auto" px={[1, 2, 3, 4]}>
              <Navbar />
            </Box>
          </Box>
          <Box maxW="1170px" margin="auto" px={[1, 2, 2, 4]} my={4}>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}

